# Generated by Django 3.1.7 on 2021-03-20 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='main_content1',
            field=models.TextField(default='Main Content', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='main_content2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subheading1',
            field=models.TextField(default='Subheading', max_length=55),
        ),
        migrations.AddField(
            model_name='post',
            name='subheading2',
            field=models.TextField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blog', max_length=55),
        ),
    ]
