# Generated by Django 3.1.7 on 2021-03-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210322_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='main_content3',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='main_content_extra',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subheading3',
            field=models.TextField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='info',
            field=models.CharField(default='Summary', max_length=155),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content1',
            field=models.TextField(default='Main Content', max_length=355),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content2',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
    ]
