# Generated by Django 3.1.7 on 2021-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210313_1408'),
        ('blog', '0006_auto_20210322_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to='profiles.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content2',
            field=models.TextField(blank=True, default='Main Content2', max_length=355),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content3',
            field=models.TextField(blank=True, default='Main Content3', max_length=355),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content_extra',
            field=models.TextField(blank=True, default='Main Content Extra', max_length=355),
        ),
        migrations.AlterField(
            model_name='post',
            name='subheading2',
            field=models.TextField(blank=True, default='Subheading2', max_length=55),
        ),
        migrations.AlterField(
            model_name='post',
            name='subheading3',
            field=models.TextField(blank=True, default='Subheading3', max_length=55),
        ),
    ]
