# Generated by Django 3.1.7 on 2021-03-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
