# Generated by Django 3.1.7 on 2021-03-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_brand_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name_plural': 'Watches'},
        ),
        migrations.AddField(
            model_name='watch',
            name='label',
            field=models.CharField(choices=[('P', 'PRIMARY'), ('S', 'SECONDARY'), ('D', 'DANGER')], default='SOME STRING', max_length=20),
        ),
    ]
