# Generated by Django 3.1.7 on 2021-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_auto_20210301_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
