# Generated by Django 3.1.7 on 2021-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_auto_20210302_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='watch',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
