# Generated by Django 3.1.7 on 2021-03-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0008_auto_20210303_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='label',
            field=models.CharField(choices=[('New', 'PRIMARY'), ('Discount', 'SECONDARY'), ('Sold', 'DANGER')], default='SOME STRING', max_length=20),
        ),
    ]
