# Generated by Django 3.1.7 on 2021-03-29 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watches', '0009_auto_20210318_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='label',
            field=models.CharField(blank=True, choices=[('New', 'PRIMARY'), ('Discount', 'SECONDARY'), ('Sold', 'DANGER')], default='SOME STRING', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='watches.watch')),
            ],
        ),
    ]
