# Generated by Django 3.1.7 on 2021-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0010_auto_20210329_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='name',
        ),
    ]
