# Generated by Django 3.1.7 on 2021-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0011_auto_20210329_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='label',
            field=models.CharField(choices=[('New', 'PRIMARY'), ('Discount', 'SECONDARY'), ('Sold', 'DANGER')], default='SOME STRING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
