# Generated by Django 3.1.7 on 2021-03-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watch',
            name='label',
            field=models.CharField(blank=True, choices=[('New', 'PRIMARY'), ('Discount', 'SECONDARY'), ('Sold', 'DANGER')], default='SOME STRING', max_length=20, null=True),
        ),
    ]
