# Generated by Django 3.1.7 on 2021-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0014_auto_20210329_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watch_information',
            field=models.TextField(default='BASIC INFORMATION'),
        ),
    ]
